version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "villaUtils"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jx3h3o6mj7ty"
s3_prefix = "villaUtils"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
